#!/bin/sh

set -e

USER_ID=$(id -u)
USER_NAME=$(id -nu)
USER_GID=$(id -g)

JAIL_ROOT="/srv/jail/${USER_NAME}"

if [ ! -d "$JAIL_ROOT" ]; then
    cd "${HOME}"
    exec /bin/sh "$@"
    exit 0
fi

export PS1="${USER_NAME}$ "
export HOME="/home/${USER_NAME}"
export USER="${USER_NAME}"

exec /usr/sbin/chroot "$JAIL_ROOT" /bin/sh -l "$@"
