#
# This is the main Apache HTTP server configuration file. It contains the
# configuration directives that give the server its instructions.
# See <URL:http://httpd.apache.org/docs/2.4/> for detailed information.
#
# Configuration and logfile names:
# If the filenames you specify for many of the server's control files begin 
# with "/", the server will use that explicit path. If the filenames do *not*
# begin with "/", the value of ServerRoot is prepended.
#

# It is split into several files forming the configuration hierarchy outlined
# below, all located in the /usr/local/etc/apache24/ directory:
#
#	/usr/local/etc/apache24/
#	|-- apache2.conf
#	|-- ports.conf
#	|-- modules.d/          # 模块加载配置目录
#	|   |-- *.load          # 模块加载文件
#	|   `-- *.conf          # 模块配置文件
#	|-- conf.d/             # 全局配置目录
#	|   |-- *.conf          # 全局配置文件
#	|   `-- domains/        # 域名配置目录
#	|       `-- *.conf      # 域名配置文件
#	`-- Includes/           # 额外包含目录
#	    `-- *.conf          # 自定义配置文件

# Global configuration
PidFile ${APACHE_PID_FILE}
Timeout 30
KeepAlive Off
MaxKeepAliveRequests 100
KeepAliveTimeout 10

<IfModule mpm_prefork_module>
    StartServers          8
    MinSpareServers       5
    MaxSpareServers      20
    ServerLimit         256
    MaxRequestWorkers    200
    MaxRequestsPerChild 4000
</IfModule>

<IfModule mpm_worker_module>
    StartServers          2
    MinSpareThreads      25
    MaxSpareThreads      75
    ThreadLimit          64
    ThreadsPerChild      25
    MaxRequestWorkers    200
    MaxRequestsPerChild 4000
</IfModule>

<IfModule mpm_event_module>
    StartServers          2
    MinSpareThreads      25
    MaxSpareThreads      75
    ThreadLimit          64
    ThreadsPerChild      25
    MaxRequestWorkers    200
    MaxRequestsPerChild 4000
</IfModule>

# These need to be set in /usr/local/sbin/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}
#User www
#Group www

AccessFileName .htaccess

<Files ~ "^\.ht">
    Require all denied
</Files>

DefaultType None
HostnameLookups Off

ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn

# Include module configuration (FreeBSD style)
IncludeOptional modules.d/*.load
IncludeOptional modules.d/*.conf

# Include list of ports to listen on and which to use for name based vhosts
IncludeOptional ports.conf

LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
LogFormat "%b" bytes

IncludeOptional conf.d/*.conf
IncludeOptional conf.d/domains/webmail.*.conf
IncludeOptional conf.d/domains/*.conf
# Include the virtual host configurations:
#Include sites-enabled/
ErrorDocument 403 /error/403.html
ErrorDocument 404 /error/404.html
ErrorDocument 500 /error/50x.html
ErrorDocument 501 /error/50x.html
ErrorDocument 502 /error/50x.html
ErrorDocument 503 /error/50x.html
ErrorDocument 506 /error/50x.html