# FreeBSD newsyslog configuration for Roundcube Webmail
# [log_file_path]                  [owner:group]  [mode] [count] [size] [when] [flags] [/pid_file_path]
/var/log/roundcube/errors.log      mailnull:www   640    12      *      $M1D0  G       Z
/var/log/roundcube/sendmail.log    mailnull:www   640    12      *      $M1D0  G       Z